### ISSUE TITLE
No prebuilt images containing this plugin

### ISSUE THREAD

**Issue by petiepooo** [opendistro-for-elasticsearch/security-advanced-modules#2]
Please consider releasing a dockerhub image of kibana with this plugin preinstalled.  Alternatively, hosting the compiled plugin as a zipfile that can be installed directly by the elasticsearch-plugin binary would help tremendously for us non-Java devs.

I don't have a ready-built dev environment with Maven and all related tools to be able to compile this myself.  Nor could I find explicit instructions on how to setup a dev environment and compile it; only how to build a new docker image with one more plugin installed.  I'm sure it's easy for a java dev, and someone well-versed on these tools, but not for a data analyst or end user...

BTW, thanks for releasing this!  I've been looking for a solution just like this.  It's a shame that ElasticCo considers security an enterprise-only feature, not a necessary basic function.

**Comment by hardik-k-shah** [comment]
Hi @petiepooo,  This repository (security-advanced-modules) and all other security repository (security-parent, security-ssl and security) are part of single Security plugin and it come per-installed in our dockerhub image. 

Additionally, security-kibana-plugin come pre-installed with our kibana dockerhub image. 

I hope this helps.

**Comment by hardik-k-shah** [comment]
Additionally, you can find steps to install

Open Distro for Elasticsearch through docker: https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/

And Open Distro Kibana through docker: https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/

These will install Open Distro for Elasticsearch, Kibana and all required plugin including Security, Performance Analyzer, SQL and Alerting.
