### ISSUE TITLE
SAML config issue

### ISSUE THREAD

**Issue by hermanhmlee** [opendistro-for-elasticsearch/security-advanced-modules#3]
I followed the instruction on
https://opendistro.github.io/for-elasticsearch-docs/docs/security/saml/
and configured config.yml to almost the same as the minimal configuration example on the page
and have added
opendistro_security.auth.type: "saml"
and
server.xsrf.whitelist: ["/opendistro_security/saml/acs", "/opendistro_security/saml/logout"]
to kibana.yml as well.

But I am getting the error :
SAML configuration error
Something went wrong while retrieving the SAML configuration, please check your settings.

What could be wrong? How do I  get log4j to log the errors in com.amazon.dlic.auth.http.saml.HttpSamlAuthenticator.java? I already have the root logger in /etc/elasticsearch/log4j2.properties set to debug but I still don't see anything in /var/log/elasticsearch/elasticsearch.log

**Comment by NihalHarish** [comment]
Hi!

Can you try with:

`server.xsrf.whitelist: ["/_opendistro/_security/saml/acs", "/opendistro_security/saml/logout"]`

**Comment by hermanhmlee** [comment]
nothing changed with that change....i restarted my servers as well

**Comment by NihalHarish** [comment]
Can you share your entire kibana.yml

**Comment by hermanhmlee** [comment]
server.port: 5601
server.host:10.0.0.1

#elasticsearch.url: https://localhost:9200
elasticsearch.url: https://10.0.0.1:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

opendistro_security.multitenancy.enabled: true
opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

opendistro_security.auth.type: "saml"
server.xsrf.whitelist: ["/_opendistro/_security/saml/acs", "/opendistro_security/saml/logout"]

logging.verbose: true
logging.dest: /var/log/kibana/mylog.log

**Comment by NihalHarish** [comment]
Can you also share your elasticsearch.yml?

**Comment by hermanhmlee** [comment]
it's just the default one - i didn't change anything there

**Comment by NihalHarish** [comment]
Can you share your config.yml?

**Comment by hermanhmlee** [comment]
it's the default one plus these lines:

      saml:
        enabled: true
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_file: IdP.xml
              entity_id: idp_entityId
            sp:
              entity_id: sp_entityId
              signature_algorithm: RSA_SHA512
              forceAuthn: false
            kibana_url: http://10.0.0.1:5601/
            roles_key: Role
            exchange_key: 'abcdefghijklmnopqrstuvwxyzabcdef'
        authentication_backend:
          type: noop


I have changed some values like entity ids and ip addresses to dummy values here but in fact they are real values matching the SAML metadata. Exchange key is some other 32 characters value

**Comment by hermanhmlee** [comment]
there's some inconsistencies here:
https://opendistro.github.io/for-elasticsearch-docs/docs/security/saml/
sometimes it says saml: in the yaml file, sometimes it says saml_auth_domain: 
neither work though

**Comment by aetter** [comment]
Hi @hermanhmlee, I'm afraid I don't have much help to offer, but the `saml` vs. `saml_auth_domain` shouldn't be the problem. You can use any name you like for each entry in the `authc` and `authz` sections. I'll make them consistent in the document to avoid further confusion, at least.

**Comment by hermanhmlee** [comment]
Thanks @aetter, yes, that makes sense  - I just realized earlier today too that the name doesn't matter.

**Comment by aetter** [comment]
@hermanhmlee, thanks for the quick reply, and sorry for the rough experience here. I know it doesn't help you in the moment, but if you get this working, I'd love some suggestions for/help on the documentation. There are just so many variables to consider, many of which are on the IdP side of the house. I'll see if I can get SAML up and running on my end in the coming week so that I can help more with troubleshooting.

**Comment by hermanhmlee** [comment]
I did some remote debugging of the security advanced module. It seems to be using index based configuration rather than reading from my config.yml

**Comment by hermanhmlee** [comment]
finally got it working by forcing the elasticsesarch index storing the configurations to be refreshed from config.yml

this is the command I used:

 ./securityadmin.sh -f ../securityconfig/config.yml -icl -nhnv -cert /etc/elasticsearch/kirk.pem -cacert /etc/elasticsearch/root-ca.pem -h <ip address> -key /etc/elasticsearch/kirk-key.pem -t config

**Comment by ghost** [comment]
@hermanhmlee / @NihalHarish - I am facing the same issue with SAML integration, the kibana_url is being proxy passed through a nginx machine. Can that cause any issues? 

Here is the elasticsearch.yml

```
saml:
        enabled: true
        order: 0
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
             metadata_file: okta-metadata.xml
             entity_id: http://www.okta.com/kdjaejdlakedlkaweldase
            sp:
             entity_id: kibana-saml
            roles_key: 'Roles'
            kibana_url: https://kibana.example.com
            exchange_key: '12jn3l1j2n3l1kn2l3kn1l2kn312'
        authentication_backend:
          type: noop
``` 

And here is the kibana.yml

```
opendistro_security.auth.type: "saml"

server.xsrf.whitelist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
```

**Comment by hermanhmlee** [comment]
@srinivasanant, if you haven't already, you can try to change challenge to false for the other authenticators in config.yml
